const quotes = [
    { text: "Be yourself; everyone else is already taken.", author: "Oscar Wilde" },
    { text: "Two things are infinite: the universe and human stupidity; and I'm not sure about the universe.", author: "Albert Einstein" },
    { text: "So many books, so little time.", author: "Frank Zappa" },
    { text: "A room without books is like a body without a soul.", author: "Marcus Tullius Cicero" },
    { text: "In three words I can sum up everything I've learned about life: it goes on.", author: "Robert Frost" },
    { text: "If you tell the truth, you don't have to remember anything.", author: "Mark Twain" },
    { text: "Without music, life would be a mistake.", author: "Friedrich Nietzsche" },
    { text: "We accept the love we think we deserve.", author: "Stephen Chbosky" },
    { text: "To live is the rarest thing in the world. Most people exist, that is all.", author: "Oscar Wilde" },
    { text: "I am so clever that sometimes I don't understand a single word of what I am saying.", author: "Oscar Wilde" },
    { text: "Insanity is doing the same thing, over and over again, but expecting different results.", author: "Narcotics Anonymous" },
    { text: "It is better to be hated for what you are than to be loved for what you are not.", author: "André Gide" },
    { text: "Good friends, good books, and a sleepy conscience: this is the ideal life.", author: "Mark Twain" },
    { text: "Life is what happens to us while we are making other plans.", author: "Allen Saunders" },
    { text: "Everything you can imagine is real.", author: "Pablo Picasso" },
    { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
    { text: "It does not do to dwell on dreams and forget to live.", author: "J.K. Rowling" },
    { text: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt" },
    { text: "Success is not final, failure is not fatal: It is the courage to continue that counts.", author: "Winston S. Churchill" },
    { text: "Success is how high you bounce when you hit bottom.", author: "George S. Patton" },
    { text: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau" },
    { text: "You only live once, but if you do it right, once is enough.", author: "Mae West" },
    { text: "The purpose of life is not to be happy. It is to be useful, to be honorable, to be compassionate, to have it make some difference that you have lived and lived well.", author: "Ralph Waldo Emerson" },
    { text: "It is never too late to be what you might have been.", author: "George Eliot" },
    { text: "Life isn't about finding yourself. Life is about creating yourself.", author: "George Bernard Shaw" },
    { text: "Do not go where the path may lead, go instead where there is no path and leave a trail.", author: "Ralph Waldo Emerson" },
    { text: "You miss 100% of the shots you don't take.", author: "Wayne Gretzky" },
    { text: "The best time to plant a tree was 20 years ago. The second best time is now.", author: "Chinese Proverb" },
    { text: "Your time is limited, so don't waste it living someone else's life.", author: "Steve Jobs" },
    { text: "Not all those who wander are lost.", author: "J.R.R. Tolkien" },
    { text: "If life were predictable it would cease to be life, and be without flavor.", author: "Eleanor Roosevelt" },
    { text: "If you look at what you have in life, you'll always have more. If you look at what you don't have in life, you'll never have enough.", author: "Oprah Winfrey" },
    { text: "Life is either a daring adventure or nothing at all.", author: "Helen Keller" },
    { text: "Go confidently in the direction of your dreams. Live the life you have imagined.", author: "Henry David Thoreau" },
    { text: "In the end, we will remember not the words of our enemies, but the silence of our friends.", author: "Martin Luther King Jr." },
    { text: "Do not let making a living prevent you from making a life.", author: "John Wooden" },
    { text: "Life is made of ever so many partings welded together.", author: "Charles Dickens" },
    { text: "Love the life you live. Live the life you love.", author: "Bob Marley" },
    { text: "Keep calm and carry on.", author: "Winston Churchill" },
    { text: "There are no mistakes, only opportunities.", author: "Tina Fey" },
    { text: "It always seems impossible until it's done.", author: "Nelson Mandela" },
    { text: "To love and be loved is to feel the sun from both sides.", author: "David Viscott" },
    { text: "Be kind whenever possible. It is always possible.", author: "Dalai Lama" },
    { text: "The most wasted of days is one without laughter.", author: "E.E. Cummings" },
    { text: "Life is short, and it is up to you to make it sweet.", author: "Sarah Louise Delany" },
    { text: "You can't use up creativity. The more you use, the more you have.", author: "Maya Angelou" },
    { text: "Live in the sunshine, swim the sea, drink the wild air.", author: "Ralph Waldo Emerson" },
    { text: "Life itself is the most wonderful fairy tale.", author: "Hans Christian Andersen" },
    { text: "Do not wait to strike till the iron is hot; but make it hot by striking.", author: "William Butler Yeats" },
    { text: "Live for each second without hesitation.", author: "Elton John" },
    { text: "In the middle of difficulty lies opportunity.", author: "Albert Einstein" }
]
  


export default quotes;